steps:
- name: 'gcr.io/cloud-builders/docker'
  id: Build
  args:
    - 'build'
    - '-t'
    - 'asia.gcr.io/searce-playground-v1/shubham-versioning:$SHORT_SHA'
    - '.'
- name: 'gcr.io/cloud-builders/docker'
  id: Push
  args:
    - 'push'
    - 'asia.gcr.io/searce-playground-v1/shubham-versioning:$SHORT_SHA'
logsBucket: 'gs://shubham-bucket-cloudbuild'
