steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build','-t','asia.gcr.io/searce-playground-v1/shubham-cloudbuild-test-image:latest','.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push','asia.gcr.io/searce-playground-v1/shubham-cloudbuild-test-image:latest']
images: ['asia.gcr.io/searce-playground-v1/shubham-cloudbuild-test-image:latest']
logsBucket: 'gs://shubham-bucket-cloudbuild'
